version: 1
update_configs:
  - package_manager: 'javascript'
    target_branch: 'master'
    directory: '/'
    update_schedule: 'daily'
    allowed_updates:
      - match:
          update_type: 'security'
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'